PLAYER1 = "-1"
NO_MOVE = "0"
PLAYER2 = "1"

ALLOWED_CHOICES = ((PLAYER1, PLAYER1), (PLAYER2, PLAYER2), (NO_MOVE, NO_MOVE))

DRAW = "0"
ALLOWED_WINNER = ((PLAYER1, PLAYER1), (PLAYER2, PLAYER2), (DRAW, DRAW))
