# Generated by Django 3.2.1 on 2021-05-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("game", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="gamedetails",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_detail",
                to="game.userdetail",
            ),
        )
    ]
