# Generated by Django 3.2.1 on 2021-05-05 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("game", "0002_alter_gamedetails_user")]

    operations = [
        migrations.AlterField(
            model_name="gamedetails",
            name="game_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="user_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
