# Generated by Django 3.2.1 on 2021-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("game", "0003_auto_20210505_1754")]

    operations = [
        migrations.AlterField(
            model_name="gamedetails",
            name="winner",
            field=models.CharField(
                choices=[("-1", "-1"), ("1", "1"), ("0", "0")],
                default="0",
                max_length=10,
            ),
        )
    ]
